import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

// const nunito = Nunito({
//   weight: "400",
//   subsets: ["latin"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next appIntroduction to Next.js",
  icons: {
    icon: "/favicon.ico", // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto} antialiased`}
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Head>
          {/* Favicon im Head einfügen */}
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav> Home</nav>
        {children}
      </body>
    </html>
  );
}
